"""
find_adoption_date.py

Detect the earliest date a repo adopted AI coding tools, using two signals:
  1. Commit messages containing AI attribution patterns
  2. AI config files appearing in git history

Returns ISO date string or None.

Usage:
    python find_adoption_date.py --repo /path/to/repo
    python find_adoption_date.py --repo /path/to/repo --verbose
"""

import re
import subprocess
import argparse
from datetime import datetime, timezone
from pathlib import Path

COMMIT_PATTERNS = [
    # Cursor agent attribution
    r"co-authored-by:\s*cursor\b",
    r"cursoragent@cursor\.com",
    # GitHub Copilot attribution
    r"co-authored-by:\s*copilot\b",
    r"co-authored-by:.*github-copilot",
    r"copilot@github\.com",
    # Claude AI attribution (must include domain or "AI" qualifier, not human names)
    r"co-authored-by:\s*claude\s+claude@anthropic",
    r"noreply@anthropic\.com",
    r"claude-code",
    # Generic AI generation markers
    r"generated with claude\b",
    r"generated with copilot\b",
    r"generated with gpt\b",
    r"generated by claude\b",
    r"generated by copilot\b",
    r"generated by gpt\b",
    r"\U0001f916\s*generated",   # 🤖 Generated
    r"vibe.cod",
    r"cursor agent",
    r"copilot agent",
]

CONFIG_FILES = [
    ".cursor/rules",
    ".cursor/settings.json",
    ".github/copilot-instructions.md",
    "CLAUDE.md",
    ".copilot/",
    "copilot-instructions.md",
]

_COMMIT_RE = re.compile("|".join(COMMIT_PATTERNS), re.IGNORECASE)


def _git(repo: Path, *args) -> str:
    result = subprocess.run(
        ["git", "-C", str(repo)] + list(args),
        capture_output=True, text=True, errors="ignore"
    )
    return result.stdout.strip()


def earliest_commit_signal(repo: Path, verbose: bool = False) -> datetime | None:
    log = _git(repo, "log", "--all", "--format=%ai %s %b")
    earliest = None
    for line in log.splitlines():
        parts = line.split(" ", 3)
        if len(parts) < 4:
            continue
        date_str = parts[0] + " " + parts[1] + " " + parts[2]
        message = parts[3]
        if _COMMIT_RE.search(message):
            try:
                dt = datetime.fromisoformat(date_str)
                if earliest is None or dt < earliest:
                    earliest = dt
                    if verbose:
                        print(f"  [commit signal] {dt.date()}  {message[:80]}")
            except ValueError:
                continue
    return earliest


def earliest_config_signal(repo: Path, verbose: bool = False) -> datetime | None:
    earliest = None
    for cfg in CONFIG_FILES:
        # git log for first time this path was added
        out = _git(repo, "log", "--all", "--diff-filter=A",
                   "--format=%ai", "--", cfg)
        for line in out.splitlines():
            line = line.strip()
            if not line:
                continue
            try:
                dt = datetime.fromisoformat(line)
                if earliest is None or dt < earliest:
                    earliest = dt
                    if verbose:
                        print(f"  [config signal] {dt.date()}  {cfg}")
            except ValueError:
                continue
    return earliest


def find_adoption_date(repo: Path, verbose: bool = False) -> str | None:
    commit_dt = earliest_commit_signal(repo, verbose)
    config_dt = earliest_config_signal(repo, verbose)

    candidates = [d for d in [commit_dt, config_dt] if d is not None]
    if not candidates:
        return None
    return min(candidates).date().isoformat()


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--repo", required=True)
    parser.add_argument("--verbose", action="store_true")
    args = parser.parse_args()

    repo = Path(args.repo)
    date = find_adoption_date(repo, args.verbose)
    if date:
        print(f"Adoption date: {date}")
    else:
        print("No AI adoption signal found.")


if __name__ == "__main__":
    main()
