"""
find_adoption_date.py

Detect the earliest date a repo shows DECLARED AI attribution, using two
signals:
  1. Commit messages containing AI attribution trailers/markers
     (e.g. "Co-authored-by: ... noreply@anthropic.com")
  2. AI config files appearing in git history

This measures declared attribution, not actual tool adoption: a contributor
using an AI coding tool without adding an attribution trailer is invisible to
this detector. Silent (undeclared) adoption is out of scope for this project.
A validation pass comparing this regex against a semantic LLM judge (Jev,
typesafe/jev-1.13) over 1,275 sampled real commits found 0 disagreements
(see data/trials/pf_hist_result.json) — i.e. no commit in that sample used AI
tooling without also declaring it in the message. That result is evidence the
regex is sufficient for the *declared* signal, not evidence that silent
adoption doesn't happen elsewhere.

Returns ISO date string (of first declared attribution) or None.

Usage:
    python find_adoption_date.py --repo /path/to/repo
    python find_adoption_date.py --repo /path/to/repo --verbose
"""

import re
import subprocess
import argparse
from datetime import datetime, timezone
from pathlib import Path

COMMIT_PATTERNS = [
    # Cursor agent attribution
    r"co-authored-by:\s*cursor\b",
    r"cursoragent@cursor\.com",
    # GitHub Copilot attribution
    r"co-authored-by:\s*copilot\b",
    r"co-authored-by:.*github-copilot",
    r"copilot@github\.com",
    # Claude AI attribution (must include domain or "AI" qualifier, not human names)
    r"co-authored-by:\s*claude\s+claude@anthropic",
    r"noreply@anthropic\.com",
    r"claude-code",
    # Generic AI generation markers
    r"generated with claude\b",
    r"generated with copilot\b",
    r"generated with gpt\b",
    r"generated by claude\b",
    r"generated by copilot\b",
    r"generated by gpt\b",
    r"\U0001f916\s*generated",   # 🤖 Generated
    r"vibe.cod",
    r"cursor agent",
    r"copilot agent",
]

CONFIG_FILES = [
    ".cursor/rules",
    ".cursor/settings.json",
    ".github/copilot-instructions.md",
    "CLAUDE.md",
    ".copilot/",
    "copilot-instructions.md",
]

_COMMIT_RE = re.compile("|".join(COMMIT_PATTERNS), re.IGNORECASE)


def _git(repo: Path, *args) -> str:
    result = subprocess.run(
        ["git", "-C", str(repo)] + list(args),
        capture_output=True, text=True, errors="ignore"
    )
    return result.stdout.strip()


_FIELD_SEP = "\x1f"
_RECORD_SEP = "\x1e"


def earliest_commit_signal(repo: Path, verbose: bool = False) -> datetime | None:
    """Scan full commit messages (subject + body) for AI attribution signals.

    Uses NUL-free field/record separators rather than naive whitespace
    splitting, since a plain `%ai %s %b` + splitlines() approach only tests
    each commit's first line against the regex — attribution trailers placed
    later in a multi-line body (the normal position for `Co-authored-by:`
    lines) were silently invisible to the old implementation.
    """
    fmt = f"%ai{_FIELD_SEP}%s{_FIELD_SEP}%b{_RECORD_SEP}"
    log = _git(repo, "log", "--all", f"--format={fmt}")
    earliest = None
    for record in log.split(_RECORD_SEP):
        record = record.strip("\n")
        if not record:
            continue
        parts = record.split(_FIELD_SEP)
        if len(parts) < 3:
            continue
        date_str, subject, body = parts[0], parts[1], parts[2]
        message = subject + "\n" + body
        if _COMMIT_RE.search(message):
            try:
                dt = datetime.fromisoformat(date_str)
                if earliest is None or dt < earliest:
                    earliest = dt
                    if verbose:
                        print(f"  [commit signal] {dt.date()}  {subject[:80]}")
            except ValueError:
                continue
    return earliest


def earliest_config_signal(repo: Path, verbose: bool = False) -> datetime | None:
    earliest = None
    for cfg in CONFIG_FILES:
        # git log for first time this path was added
        out = _git(repo, "log", "--all", "--diff-filter=A",
                   "--format=%ai", "--", cfg)
        for line in out.splitlines():
            line = line.strip()
            if not line:
                continue
            try:
                dt = datetime.fromisoformat(line)
                if earliest is None or dt < earliest:
                    earliest = dt
                    if verbose:
                        print(f"  [config signal] {dt.date()}  {cfg}")
            except ValueError:
                continue
    return earliest


def find_adoption_date(repo: Path, verbose: bool = False) -> str | None:
    """Return the ISO date of the earliest declared-AI-attribution signal, or None."""
    commit_dt = earliest_commit_signal(repo, verbose)
    config_dt = earliest_config_signal(repo, verbose)

    candidates = [d for d in [commit_dt, config_dt] if d is not None]
    if not candidates:
        return None
    return min(candidates).date().isoformat()


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--repo", required=True)
    parser.add_argument("--verbose", action="store_true")
    args = parser.parse_args()

    repo = Path(args.repo)
    date = find_adoption_date(repo, args.verbose)
    if date:
        print(f"Declared attribution date: {date}")
    else:
        print("No declared AI attribution signal found.")


if __name__ == "__main__":
    main()
