"""
find_adoption_date.py

Detect the earliest date a repo shows DECLARED AI attribution, using two
signals:
  1. Commit messages containing AI attribution trailers/markers
     (e.g. "Co-authored-by: ... noreply@anthropic.com")
  2. AI config files appearing in git history

This measures declared attribution. A contributor who uses an AI coding tool
without adding an attribution trailer is invisible to this detector, and to any
detector that reads only commit messages; that case is out of scope.
On 1,275 sampled commits, this regex and an LLM classifier reading the same
messages (Jev, typesafe/jev-1.13) flagged the same 116 commits
(data/trials/pf_hist_result.json), so no semantic classifier is used.

Returns ISO date string (of first declared attribution) or None.

Usage:
    python find_adoption_date.py --repo /path/to/repo
    python find_adoption_date.py --repo /path/to/repo --verbose
    python find_adoption_date.py --repo /path/to/repo --rev HEAD   # history of the checked-out snapshot only
"""

import re
import subprocess
import argparse
from datetime import datetime, timezone
from pathlib import Path

COMMIT_PATTERNS = [
    # Cursor agent attribution
    r"co-authored-by:\s*cursor\b",
    r"cursoragent@cursor\.com",
    # GitHub Copilot attribution
    r"co-authored-by:\s*copilot\b",
    r"co-authored-by:.*github-copilot",
    r"copilot@github\.com",
    # Claude AI attribution (must include domain or "AI" qualifier, not human names)
    r"co-authored-by:\s*claude\s+claude@anthropic",
    r"noreply@anthropic\.com",
    r"claude-code",
    # Generic AI generation markers
    r"generated with claude\b",
    r"generated with copilot\b",
    r"generated with gpt\b",
    r"generated by claude\b",
    r"generated by copilot\b",
    r"generated by gpt\b",
    r"\U0001f916\s*generated",   # 🤖 Generated
    r"vibe.cod",
    r"cursor agent",
    r"copilot agent",
]

CONFIG_FILES = [
    ".cursor/rules",
    ".cursor/settings.json",
    ".github/copilot-instructions.md",
    "CLAUDE.md",
    ".copilot/",
    "copilot-instructions.md",
]

_COMMIT_RE = re.compile("|".join(COMMIT_PATTERNS), re.IGNORECASE)


def _git(repo: Path, *args) -> str:
    result = subprocess.run(
        ["git", "-C", str(repo)] + list(args),
        capture_output=True, text=True, errors="ignore"
    )
    return result.stdout.strip()


_FIELD_SEP = "\x1f"
_RECORD_SEP = "\x1e"


def earliest_commit_signal(repo: Path, verbose: bool = False, rev: str = "--all") -> datetime | None:
    # Control-char separators keep multi-line bodies intact; trailers usually sit at the end.
    fmt = f"%ai{_FIELD_SEP}%s{_FIELD_SEP}%b{_RECORD_SEP}"
    log = _git(repo, "log", rev, f"--format={fmt}")
    earliest = None
    for record in log.split(_RECORD_SEP):
        record = record.strip("\n")
        if not record:
            continue
        parts = record.split(_FIELD_SEP)
        if len(parts) < 3:
            continue
        date_str, subject, body = parts[0], parts[1], parts[2]
        message = subject + "\n" + body
        if _COMMIT_RE.search(message):
            try:
                dt = datetime.fromisoformat(date_str)
                if earliest is None or dt < earliest:
                    earliest = dt
                    if verbose:
                        print(f"  [commit signal] {dt.date()}  {subject[:80]}")
            except ValueError:
                continue
    return earliest


def earliest_config_signal(repo: Path, verbose: bool = False, rev: str = "--all") -> datetime | None:
    earliest = None
    for cfg in CONFIG_FILES:
        # git log for first time this path was added
        out = _git(repo, "log", rev, "--diff-filter=A",
                   "--format=%ai", "--", cfg)
        for line in out.splitlines():
            line = line.strip()
            if not line:
                continue
            try:
                dt = datetime.fromisoformat(line)
                if earliest is None or dt < earliest:
                    earliest = dt
                    if verbose:
                        print(f"  [config signal] {dt.date()}  {cfg}")
            except ValueError:
                continue
    return earliest


def find_adoption_date(repo: Path, verbose: bool = False, rev: str = "--all") -> str | None:
    """Return the ISO date of the earliest declared-AI-attribution signal, or None."""
    commit_dt = earliest_commit_signal(repo, verbose, rev)
    config_dt = earliest_config_signal(repo, verbose, rev)

    candidates = [d for d in [commit_dt, config_dt] if d is not None]
    if not candidates:
        return None
    return min(candidates).date().isoformat()


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--repo", required=True)
    parser.add_argument("--verbose", action="store_true")
    parser.add_argument("--rev", default="--all",
                        help="history to scan: --all (every ref) or a ref such as HEAD (paper v1.1 uses HEAD, the snapshot)")
    args = parser.parse_args()

    repo = Path(args.repo)
    date = find_adoption_date(repo, args.verbose, args.rev)
    if date:
        print(f"Declared attribution date: {date}")
    else:
        print("No declared AI attribution signal found.")


if __name__ == "__main__":
    main()
